CREATE TABLE IF NOT EXISTS contenido (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  clave VARCHAR(150) NOT NULL,
  valor TEXT NOT NULL,
  tipo VARCHAR(30) NOT NULL DEFAULT 'texto',
  etiqueta VARCHAR(200) NOT NULL,
  grupo VARCHAR(100) NOT NULL DEFAULT 'General',
  activo TINYINT(1) NOT NULL DEFAULT 1,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_contenido_clave (clave),
  KEY idx_contenido_grupo (grupo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
